### ISSUE TITLE
Maximaler absoluter Fehler im nicht linearen Modell

### ISSUE THREAD

**Issue by mentalAdventurer** [FabianTsch/gantry#2]
Fehler in Verify Model sollte eigentlich auf Null gehen. Ist vermutlich einfach ein Typo in der definition des Systems.

```
Maximaler absoluter Fehler in Modellgleichung (euklidische Norm): 0.05812513894480276
```

**Comment by NSB4130** [comment]
![image](https://user-images.githubusercontent.com/122178090/214515071-3e600177-3f58-47cd-afc1-2256225a70bc.png)

Index in Notebook flasch, in Code richtig

**Comment by NSB4130** [comment]
Vorzeichenfehler in Code

**Comment by FabianTsch** [comment]
> ![image](https://user-images.githubusercontent.com/122178090/214515071-3e600177-3f58-47cd-afc1-2256225a70bc.png)
> 
> Index in Notebook flasch, in Code richtig

Sollen wir das aus bessern? Den Teil haben wir nicht geschrieben

**Comment by mentalAdventurer** [comment]
> Vorzeichenfehler in Code

@NSB4130 
An welcher Stelle?
Und löst das das Problem?

**Comment by NSB4130** [comment]
![image](https://user-images.githubusercontent.com/122178090/214523212-8001a3c6-ee82-4ff4-930c-9a7a1ab0d7fb.png)
 
Wenn mann die Formel aus dem Notebook verwendet, verschwindet der Fehler ganz. Wsl. sollte es dann tatsächlich dz2*dx2*m lauten

**Comment by mentalAdventurer** [comment]
:heart:  :heart: :heart:  Mega Niko!!!
