### ISSUE TITLE
Fehler in den C Matrizen C['position_total'] und  C['position_axis']

### ISSUE THREAD

**Issue by NSB4130** [FabianTsch/gantry#3]
Um die Fehler betraglich auszugleichen, müssten die Einträge in den Matrizen folgendermaßen angepasst werden:

![image](https://user-images.githubusercontent.com/122178090/213675201-12d6d292-a5f8-4363-8886-b51a33d3f1e3.png)

link:

https://github.com/FabianTsch/gantry/blob/9c951b86b54d06f3624aa95de5937260d69319f1/gantry.py#L95

**Comment by mentalAdventurer** [comment]
```
C['position_total']=np.array([[1, 0, 1, 0, -x2, 0, 0, 0, 0, 0],
                                      [0, 1, 0, 1, x1, 0, 0, 0, 0, 0]])
C['position_axis'] = np.array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                                       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])
```
In der zweiten Zeile bei `total` ist ein Vorzeichenfehler und `axis` ist generell nicht ganz richtig

**Comment by mentalAdventurer** [comment]
Ich habe den Fehler im aktuellen Pullrequest #4  ausgebessert. 
Es bleibt jedoch eine Abweichung von 1  bei `position_axis`

Ich kann den Fehler lösen indem ich die Matrix folgender maßen definiere:

```
C['position_axis'] = np.array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                               [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
```
Das ist meiner Meinung nach nicht ganz richitg
Was meinst du dazu @NSB4130?

**Comment by mentalAdventurer** [comment]
Matrixen müssen als double implementiert werden.
```
C['position_axis'] = np.array([[1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                               [0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0]])
```
